### PR TITLE
Adding AutoRefresh for token refresh

### PR DESCRIPTION
**Pull request by sthang**

### CODE REVIEW

**Comment by abisalehalliprasan** [comment]
@sthang : Thanks for the PR 👏 . Have a couple of questions with your implementation : 

- I noticed that as part of the `createToken` method, you are doing a check to see if the autoRefresh is enabled and if YES, the client sets up the `autoRefresh`. This point forward depending on the `autoRefreshIntervalInSeconds` field the auto-refresh of tokens goes on until its killed explicitly. But what if there is a call made to `OAuthClient.prototype.refresh` explicitly ? Will it process the current refresh request into a Queue ?

- You have updated the sample to stopAutoRefresh on demand as shown [here](https://github.com/intuit/oauth-jsclient/pull/56/files#diff-8b74a2d383532f3f0e047f2fea085762R101). But the actual `stopRefresh()` method is missing on the client. were you planning on updating it later?

**Comment by sthang** [comment]
@abisalehalliprasan : Thanks for the review. 

1. No. If refresh is called explicitly it will be independent of the autoRefresh and has no impact on the timer. I thought about it and made it independent to keep the implementation simple. The alternative is to reset the timer on setInterval when refresh is called outside of autoRefresh. What do you think?

2. [Here's](https://github.com/intuit/oauth-jsclient/pull/56/files#diff-792d09eae4cb053d98203faa257489c3R664) the stopRefresh on the OAuthClient. The sample app is calling it on the oauthClient.

**Comment by abisalehalliprasan** [comment]
@sthang : 

1.) We do not want the explicit token refresh call to coincide with the autoRefresh. The workaround seems fine but there is a one-off edge case where the two API calls might coincide(the probability is very low 😃). I will see if I could implement `Queue` logic here. 

Could you close this PR and create a PR for the branch `autoRefresh` . Apologize for the re-do, I need to test this feature before actually releasing it. Thanks @sthang

**Comment by sthang** [comment]
No problem. I'll reopen the PR with the branch `autoRefresh`.

**Pull request merged**
