### PR TITLE
Fix/eslint formatting

### PR DESCRIPTION
**Pull request by mcrosby114**
Addresses the all the eslint errors except the "no-undef" from #32.

### CODE REVIEW

**Comment by mcrosby114** [comment]
@abisalehalliprasan can we upgrade the version of node to something greater than 6, like version 8? Seeing there's an issue with the JS engine not recognizing `Object.entries()` (https://travis-ci.org/intuit/oauth-jsclient/jobs/593613545#L292)

**Comment by abisalehalliprasan** [comment]
> @abisalehalliprasan can we upgrade the version of node to something greater than 6, like version 8? Seeing there's an issue with the JS engine not recognizing `Object.entries()` (https://travis-ci.org/intuit/oauth-jsclient/jobs/593613545#L292).
> 
> This shows how it's incompatible with the current version of node: https://node.green/#ES2017-features-Object-static-methods-Object-entries

Yeah, I think it should be fine. I can bump a version up and release, following the sem version. 

Looks Good @mcrosby114 👍 🙌

**Comment by abisalehalliprasan** [comment]
🚀 PR was released in v2.0.0  `hacktoberfest`

**Comment by mcrosby114** [comment]
https://github.com/intuit/oauth-jsclient/pull/38#issuecomment-543935872 🙌

**Pull request merged**
