### PR TITLE
Resolved dependency issue || Axios Introduced

### PR DESCRIPTION
**Pull request by pragati0909**
https://github.com/intuit/oauth-jsclient/issues/143

Introduced Axios instead of Popsicle.

### CODE REVIEW

**Review by rajeshgupta723 — APPROVED** [review]
This looks good, thanks

**Comment by mishchief** [comment]
somebody please release this

**Comment by slawton3** [comment]
why has this not been released yet?

**Comment by NootyPenguino** [comment]
Please release this

**Comment by rajeshgupta723** [comment]
Thanks for your patience. A release branch has been created in preparation for production release.

**Comment by mishchief** [comment]
Thanks so much @rajeshgupta723 !!! Really appreciate your help! I will give this a look tomorrow or friday!

**Pull request merged**
