### PR TITLE
Adds typings

### PR DESCRIPTION
**Pull request by efredin**
Adds typescript support.  Re-opened targeting new `typescript` branch on request of @abisalehalliprasan 

In order to avoid adding external typing dependencies, I've left log() typings fairly generic. There is an @types/winston package available, but its probably not necessary.

### CODE REVIEW

**Comment by abisalehalliprasan** [comment]
Thanks @efredin will test it and get back to you

**Comment by efredin** [comment]
Anything I can contribute to help validate the typings?

**Comment by abisalehalliprasan** [comment]
@efredin : Thanks for checking with us. I am not too familiar with typescript, so would be helpful if you could show me how to use `index.d.ts` in the [sample](https://github.com/intuit/oauth-jsclient/tree/typescript/sample) 

I will be merging this PR into `typescript` branch and create a new issue for the sample. Does that work with you?

**Comment by efredin** [comment]
@abisalehalliprasan That works for me.  I should be able to put some time to this next week.  

The typings won't impact any javascript consumers.  I can update the sample in that branch to a typescript project and run it through the typescript compiler to demonstrate things are working as expected.

**Comment by abisalehalliprasan** [comment]
@efredin : Awesome thanks

**Comment by abisalehalliprasan** [comment]
🚀 PR was released in branch `typescript` for  `hacktoberfest`

**Pull request merged**
