### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by efredin**
Adds typescript support.
* In order to avoid adding external typing dependencies, I've left `log()` typings fairly generic.  There is an `@types/winston` package available, but its probably not necessary.

### CODE REVIEW

**Comment by abisalehalliprasan** [comment]
@efredin : Could you create a PR to the branch named `typescript`. I can test your changes on the separate branch hence.

**Comment by efredin** [comment]
Sure.  Do you want this PR closed?

**Comment by abisalehalliprasan** [comment]
Let me close this PR #36

**Comment by abisalehalliprasan** [comment]
🚀 PR was released in branch `typescript` for `hacktoberfest`

**Pull request closed without merging**
